# branding

branding:
  icon: 'https://example.com/icon.png'
  color: '#ffcc00'

# marketplace metadata

marketplace:
  name: 'My GitHub Action'
  description: 'This action does something awesome!'
  keywords: ['github', 'action', 'awesome']
  author: 'ZeroMergeConflicts'
  homepage: 'https://example.com'
  support: 'https://example.com/support'
